#include "stdafx.h"
#include "PCL_Def.h"

// using namespace ParsePCL;
namespace ParsePCL
{//命名空间ParsePCL开始

//操作信息表
OperatorInfo gOperatorInfoTable[] =
{
	/* not used 0x00 - 0x2f*/
	/* 0x00 nul */  {0x00, "Unknow Operator"},
	/* 0x01 soh */  {0x00, "Unknow Operator"},
	/* 0x02 stx */  {0x00, "Unknow Operator"},
	/* 0x03 etx */  {0x00, "Unknow Operator"},
	/* 0x04 eot */  {0x00, "Unknow Operator"},
	/* 0x05 enq */  {0x00, "Unknow Operator"},
	/* 0x06 ack */  {0x00, "Unknow Operator"},
	/* 0x07 bel */  {0x00, "Unknow Operator"},
	/* 0x08 bs  */  {0x00, "Unknow Operator"},
	/* 0x09 ht  */  {0x00, "Unknow Operator"},
	/* 0x0a nl  */  {0x00, "Unknow Operator"},
	/* 0x0b vt  */  {0x00, "Unknow Operator"},
	/* 0x0c np  */  {0x00, "Unknow Operator"},
	/* 0x0d cr  */  {0x00, "Unknow Operator"},
	/* 0x0e so  */  {0x00, "Unknow Operator"},
	/* 0x0f si  */  {0x00, "Unknow Operator"},
	/* 0x10 dle */  {0x00, "Unknow Operator"},
	/* 0x11 dc1 */  {0x00, "Unknow Operator"},
	/* 0x12 dc2 */  {0x00, "Unknow Operator"},
	/* 0x13 dc3 */  {0x00, "Unknow Operator"},
	/* 0x14 dc4 */  {0x00, "Unknow Operator"},
	/* 0x15 nak */  {0x00, "Unknow Operator"},
	/* 0x16 syn */  {0x00, "Unknow Operator"},
	/* 0x17 etb */  {0x00, "Unknow Operator"},
	/* 0x18 can */  {0x00, "Unknow Operator"},
	/* 0x19 em  */  {0x00, "Unknow Operator"},
	/* 0x1a sub */  {0x00, "Unknow Operator"},
	/* 0x1b esc */  {0x00, "Unknow Operator"},
	/* 0x1c fs  */  {0x00, "Unknow Operator"},
	/* 0x1d gs  */  {0x00, "Unknow Operator"},
	/* 0x1e rs  */  {0x00, "Unknow Operator"},
	/* 0x1f us  */  {0x00, "Unknow Operator"},
	/* 0x20 sp  */  {0x00, "Unknow Operator"},
	/* 0x21  !  */  {0x00, "Unknow Operator"},
	/* 0x22  "  */  {0x00, "Unknow Operator"},
	/* 0x23  #  */  {0x00, "Unknow Operator"},
	/* 0x24  $  */  {0x00, "Unknow Operator"},
	/* 0x25  %  */  {0x00, "Unknow Operator"},
	/* 0x26  &  */  {0x00, "Unknow Operator"},
	/* 0x27  '  */  {0x00, "Unknow Operator"},
	/* 0x28  (  */  {0x00, "Unknow Operator"},
	/* 0x29  )  */  {0x00, "Unknow Operator"},
	/* 0x2a  *  */  {0x00, "Unknow Operator"},
	/* 0x2b  +  */  {0x00, "Unknow Operator"},
	/* 0x2c  ,  */  {0x00, "Unknow Operator"},
	/* 0x2d  -  */  {0x00, "Unknow Operator"},
	/* 0x2e  .  */  {0x00, "Unknow Operator"},
	/* 0x2f  /  */  {0x00, "Unknow Operator"},
	/* 0x30  0  */  {0x00, "Unknow Operator"},
	/* 0x31  1  */  {0x00, "Unknow Operator"},
	/* 0x32 - 0x40 not used */
	/* 0x32  2  */  {0x00, "Unknow Operator"},
	/* 0x33  3  */  {0x00, "Unknow Operator"},
	/* 0x34  4  */  {0x00, "Unknow Operator"},
	/* 0x35  5  */  {0x00, "Unknow Operator"},
	/* 0x36  6  */  {0x00, "Unknow Operator"},
	/* 0x37  7  */  {0x00, "Unknow Operator"},
	/* 0x38  8  */  {0x00, "Unknow Operator"},
	/* 0x39  9  */  {0x00, "Unknow Operator"},
	/* 0x3a  :  */  {0x00, "Unknow Operator"},
	/* 0x3b  ;  */  {0x00, "Unknow Operator"},
	/* 0x3c  <  */  {0x00, "Unknow Operator"},
	/* 0x3d  =  */  {0x00, "Unknow Operator"},
	/* 0x3e  >  */  {0x00, "Unknow Operator"},
	/* 0x3f  ?  */  {0x00, "Unknow Operator"},
	/* 0x40  @  */  {0x00, "Unknow Operator"},
	/* 0x41  A  */  {PCL_BeginSession, "BeginSession"},
	/* 0x42  B  */  {PCL_EndSession, "EndSession"},
	/* 0x43  C  */  {PCL_BeginPage, "BeginPage"},
	/* 0x44  D  */  {PCL_EndPage, "EndPage"},
	/* 0x45  E  */  {0x00, "Unknow Operator"}, 
	/* 0x46  F  */  {0x00, "Unknow Operator"},
	/* 0x47  G  */  {PCL_Comment, "Comment"},  
	/* 0x48  H  */  {PCL_OpenDataSource, "OpenDataSource"},
	/* 0x49  I  */  {PCL_CloseDataSource, "CloseDataSource"},
	/* 0x4a  J  */  {0x00, "Unknow Operator"},
	/* 0x4b  K  */  {0x00, "Unknow Operator"},
	/* 0x4c  L  */  {0x00, "Unknow Operator"},
	/* 0x4d  M  */  {0x00, "Unknow Operator"}, 
	/* 0x4e  N  */  {0x00, "Unknow Operator"}, 
	/* 0x4f  O  */  {PCL_BeginFontHeader, "BeginFontHeader"},
	/* 0x50  P  */  {PCL_ReadFontHeader, "ReadFontHeader"},
	/* 0x51  Q  */  {PCL_EndFontHeader, "EndFontHeader"},
	/* 0x52  R  */  {PCL_BeginChar, "BeginChar"},
	/* 0x53  S  */  {PCL_ReadChar, "ReadChar"},
	/* 0x54  T  */  {PCL_EndChar, "EndChar"},
	/* 0x55  U  */  {PCL_RemoveFont, "RemoveFont"},
	/* 0x56  V  */  {PCL_SetCharAttributes, "SetCharAttributes"},     
	/* 0x57  W  */  {PCL_SetDefaultGS, "SetDefaultGS"},     
	/* 0x58  X  */  {PCL_SetColorTreatment, "SetColorTreatment"},    
	/* 0x59  Y  */  {0x00, "Unknow Operator"},    
	/* 0x5a  Z  */  {0x00, "Unknow Operator"},     
	/* 0x5b  [  */  {PCL_BeginStream, "BeginStream"},
	/* 0x5c  \  */  {PCL_ReadStream, "ReadStream"},
	/* 0x5d  ]  */  {PCL_EndStream, "EndStream"},
	/* 0x5e  ^  */  {PCL_ExecStream, "ExecStream"},
	/* 0x5f  _  */  {PCL_RemoveStream, "RemoveStream"},
	/* 0x60  `  */  {PCL_PopGS, "PopGS"},
	/* 0x61  a  */  {PCL_PushGS, "PushGS"},
	/* 0x62  b  */  {PCL_SetClipReplace, "SetClipReplace"},
	/* 0x63  c  */  {PCL_SetBrushSource, "SetBrushSource"},
	/* 0x64  d  */  {PCL_SetCharAngle, "SetCharAngle"},
	/* 0x65  e  */  {PCL_SetCharScale, "SetCharScale"},
	/* 0x66  f  */  {PCL_SetCharShear, "SetCharShear"},
	/* 0x67  g  */  {PCL_SetClipIntersect, "SetClipIntersect"},
	/* 0x68  h  */  {PCL_SetClipRectangle, "SetClipRectangle"},
	/* 0x69  i  */  {PCL_SetClipToPage, "SetClipToPage"},
	/* 0x6a  j  */  {PCL_SetColorSpace, "SetColorSpace"},
	/* 0x6b  k  */  {PCL_SetCursor, "SetCursor"},
	/* 0x6c  l  */  {PCL_SetCursorRel, "SetCursorRel"},
	/* 0x6d  m  */  {PCL_SetHalftoneMethod, "SetHalftoneMethod"},
	/* 0x6e  n  */  {PCL_SetFillMode, "SetFillMode"},
	/* 0x6f  o  */  {PCL_SetFont, "SetFont"},
	/* 0x70  p  */  {PCL_SetLineDash, "SetLineDash"},
	/* 0x71  q  */  {PCL_SetLineCap, "SetLineCap"},
	/* 0x72  r  */  {PCL_SetLineJoin, "SetLineJoin"},
	/* 0x73  s  */  {PCL_SetMiterLimit, "SetMiterLimit"},
	/* 0x74  t  */  {PCL_SetPageDefaultCTM, "SetPageDefaultCTM"},
	/* 0x75  u  */  {PCL_SetPageOrigin, "SetPageOrigin"},
	/* 0x76  v  */  {PCL_SetPageRotation, "SetPageRotation"},
	/* 0x77  w  */  {PCL_SetPageScale, "SetPageScale"},
	/* 0x78  x  */  {PCL_SetPaintTxMode, "SetPaintTxMode"},
	/* 0x79  y  */  {PCL_SetPenSource, "SetPenSource"},
	/* 0x7a  z  */  {PCL_SetPenWidth, "SetPenWidth"},
	/* 0x7b  {  */  {PCL_SetROP, "SetROP"},
	/* 0x7c  |  */  {PCL_SetSourceTxMode, "SetSourceTxMode"},
	/* 0x7d  }  */  {PCL_SetCharBoldValue, "SetCharBoldValue"},
	/* 0x7e  ~  */  {0x00, "Unknow Operator"},   
	/* 0x7f del */  {PCL_SetClipMode, "SetClipMode"},
	/* 0x80     */  {PCL_SetPathToClip, "SetPathToClip"},
	/* 0x81     */  {PCL_SetCharSubMode, "SetCharSubMode"}, 
	/* 0x82     */  {PCL_BeginUserDefinedLineCaps, "BeginUserDefinedLineCaps"},    
	/* 0x83     */  {PCL_EndUserDefinedLineCaps, "EndUserDefinedLineCaps"},
	/* 0x84     */  {PCL_CloseSubPath, "CloseSubPath"},
	/* 0x85     */  {PCL_NewPath, "NewPath"},
	/* 0x86     */  {PCL_PaintPath, "PaintPath"},
	/* 0x87     */  {0x00, "Unknow Operator"},     
	/* 0x88     */  {0x00, "Unknow Operator"},
	/* 0x89     */  {0x00, "Unknow Operator"},
	/* 0x8a     */  {0x00, "Unknow Operator"},
	/* 0x8b     */  {0x00, "Unknow Operator"},
	/* 0x8c     */  {0x00, "Unknow Operator"},
	/* 0x8d     */  {0x00, "Unknow Operator"},
	/* 0x8e     */  {0x00, "Unknow Operator"},
	/* 0x8f     */  {0x00, "Unknow Operator"},
	/* 0x90     */  {0x00, "Unknow Operator"}, 
	/* 0x91     */  {PCL_ArcPath, "ArcPath"},
	/* 0x92     */  {PCL_SetColorTrapping, "SetColorTrapping"}, 
	/* 0x93     */  {PCL_BezierPath, "BezierPath"},
	/* 0x94     */  {PCL_SetAdaptiveHalftoning, "SetAdaptiveHalftoning"}, 
	/* 0x95     */  {PCL_BezierRelPath, "BezierRelPath"},
	/* 0x96     */  {PCL_Chord, "Chord"},
	/* 0x97     */  {PCL_ChordPath, "ChordPath"},
	/* 0x98     */  {PCL_Ellipse, "Ellipse"},
	/* 0x99     */  {PCL_EllipsePath, "EllipsePath"},
	/* 0x9a     */  {0x00, "Unknow Operator"}, 
	/* 0x9b     */  {PCL_LinePath, "LinePath"},
	/* 0x9c     */  {0x00, "Unknow Operator"}, 
	/* 0x9d     */  {PCL_LineRelPath, "LineRelPath"},
	/* 0x9e     */  {PCL_Pie, "Pie"},
	/* 0x9f     */  {PCL_PiePath, "PiePath"},
	/* 0xa0     */  {PCL_Rectangle, "Rectangle"},
	/* 0xa1     */  {PCL_RectanglePath, "RectanglePath"},
	/* 0xa2     */  {PCL_RoundRectangle, "RoundRectangle"},
	/* 0xa3     */  {PCL_RoundRectanglePath, "RoundRectanglePath"},
	/* 0xa4     */  {0x00, "Unknow Operator"}, 
	/* 0xa5     */  {0x00, "Unknow Operator"}, 
	/* 0xa6     */  {0x00, "Unknow Operator"}, 
	/* 0xa7     */  {0x00, "Unknow Operator"}, 
	/* 0xa8     */  {PCL_Text, "Text"},
	/* 0xa9     */  {PCL_TextPath, "TextPath"},
	/* 0xaa     */  {0x00, "Unknow Operator"},
	/* 0xab     */  {0x00, "Unknow Operator"}, 
	/* 0xac     */  {0x00, "Unknow Operator"},
	/* 0xad     */  {0x00, "Unknow Operator"},
	/* 0xae     */  {0x00, "Unknow Operator"},
	/* 0xaf     */  {0x00, "Unknow Operator"},
	/* 0xb0     */  {PCL_BeginImage, "BeginImage"},
	/* 0xb1     */  {PCL_ReadImage, "ReadImage"},
	/* 0xb2     */  {PCL_EndImage, "EndImage"},
	/* 0xb3     */  {PCL_BeginRastPattern, "BeginRastPattern"},
	/* 0xb4     */  {PCL_ReadRastPattern, "ReadRastPattern"},
	/* 0xb5     */  {PCL_EndRastPattern, "EndRastPattern"},
	/* 0xb6     */  {PCL_BeginScan, "BeginScan"},
	/* 0xb7     */  {0x00, "Unknow Operator"},
	/* 0xb8     */  {PCL_EndScan, "EndScan"},
	/* 0xb9     */  {PCL_ScanLineRel, "ScanLineRel"},
	/* 0xba     */  {0x00, "Unknow Operator"},
	/* 0xbb     */  {0x00, "Unknow Operator"},
	/* 0xbc     */  {0x00, "Unknow Operator"},
	/* 0xbd     */  {0x00, "Unknow Operator"},
	/* 0xbe     */  {0x00, "Unknow Operator"},
	/* 0xbf     */  {PCL_PassThrough, "PassThrough"},
	/* 0xc0     */  {0x00, "Unknow Operator"},
	/* 0xc1     */  {0x00, "Unknow Operator"},
	/* 0xc2     */  {0x00, "Unknow Operator"},
	/* 0xc3     */  {0x00, "Unknow Operator"},
	/* 0xc4     */  {0x00, "Unknow Operator"},
	/* 0xc5     */  {0x00, "Unknow Operator"},
	/* 0xc6     */  {0x00, "Unknow Operator"}, 
	/* 0xc7     */  {0x00, "Unknow Operator"},
	/* 0xc8     */  {0x00, "Unknow Operator"},
	/* 0xc9     */  {0x00, "Unknow Operator"},
	/* 0xca     */  {0x00, "Unknow Operator"},
	/* 0xcb     */  {0x00, "Unknow Operator"},
	/* 0xcc     */  {0x00, "Unknow Operator"},
	/* 0xcd     */  {0x00, "Unknow Operator"},
	/* 0xce     */  {0x00, "Unknow Operator"},
	/* 0xcf     */  {0x00, "Unknow Operator"},
	/* 0xd0     */  {0x00, "Unknow Operator"},
	/* 0xd1     */  {0x00, "Unknow Operator"},
	/* 0xd2     */  {0x00, "Unknow Operator"},
	/* 0xd3     */  {0x00, "Unknow Operator"},
	/* 0xd4     */  {0x00, "Unknow Operator"},
	/* 0xd5     */  {0x00, "Unknow Operator"},
	/* 0xd6     */  {0x00, "Unknow Operator"},
	/* 0xd7     */  {0x00, "Unknow Operator"},
	/* 0xd8     */  {0x00, "Unknow Operator"},
	/* 0xd9     */  {0x00, "Unknow Operator"},
	/* 0xda     */  {0x00, "Unknow Operator"},
	/* 0xdb     */  {0x00, "Unknow Operator"},
	/* 0xdc     */  {0x00, "Unknow Operator"},
	/* 0xdd     */  {0x00, "Unknow Operator"},
	/* 0xde     */  {0x00, "Unknow Operator"},
	/* 0xdf     */  {0x00, "Unknow Operator"},
	/* 0xe0     */  {0x00, "Unknow Operator"},
	/* 0xe1     */  {0x00, "Unknow Operator"},
	/* 0xe2     */  {0x00, "Unknow Operator"},
	/* 0xe3     */  {0x00, "Unknow Operator"},
	/* 0xe4     */  {0x00, "Unknow Operator"},
	/* 0xe5     */  {0x00, "Unknow Operator"},
	/* 0xe6     */  {0x00, "Unknow Operator"},
	/* 0xe7     */  {0x00, "Unknow Operator"},
	/* 0xe8     */  {0x00, "Unknow Operator"},
	/* 0xe9     */  {0x00, "Unknow Operator"},
	/* 0xea     */  {0x00, "Unknow Operator"},
	/* 0xeb     */  {0x00, "Unknow Operator"},
	/* 0xec     */  {0x00, "Unknow Operator"},
	/* 0xed     */  {0x00, "Unknow Operator"},
	/* 0xee     */  {0x00, "Unknow Operator"},
	/* 0xef     */  {0x00, "Unknow Operator"},
	/* 0xf0     */  {0x00, "Unknow Operator"},
	/* 0xf1     */  {0x00, "Unknow Operator"},
	/* 0xf3     */  {0x00, "Unknow Operator"},
	/* 0xf4     */  {0x00, "Unknow Operator"},
	/* 0xf5     */  {0x00, "Unknow Operator"},
	/* 0xf6     */  {0x00, "Unknow Operator"},
	/* 0xf7     */  {0x00, "Unknow Operator"},
	/* 0xf8     */  {0x00, "Unknow Operator"},
	/* 0xf9     */  {0x00, "Unknow Operator"},
	/* 0xfa     */  {0x00, "Unknow Operator"},
	/* 0xfb     */  {0x00, "Unknow Operator"},
	/* 0xfc     */  {0x00, "Unknow Operator"}, /* Reserved */
	/* 0xfd     */  {0x00, "Unknow Operator"}, /* Reserved */
	/* 0xfe     */  {0x00, "Unknow Operator"}, /* Reserved */
	/* 0xff     */  {0x00, "Unknow Operator"}  /* Reserved */
};


//属性信息表
AttributeInfo gAttributeInfoTable[]=
{ 
	/*     0 */ {0x00, "Unknow Attribute"},
	/*     1 */ {0x00, "Unknow Attribute"},
	/*     2 */ {PCL_PaletteDepth, "PaletteDepth"},
	/*     3 */ {PCL_ColorSpace, "ColorSpace"},
	/*     4 */ {PCL_NullBrush, "NullBrush"},
	/*     5 */ {PCL_NullPen, "NullPen"},
	/*     6 */ {PCL_PaletteData, "PaletteData"},
	/*     7 */ {0x00, "Unknow Attribute"},
	/*     8 */ {PCL_PatternSelectID, "PatternSelectID"},
	/*     9 */ {PCL_GrayLevel, "GrayLevel"},
	/*    10 */ {0x00, "Unknow Attribute"},
	/*    11 */ {PCL_RGBColor, "RGBColor"},
	/*    12 */ {PCL_PatternOrigin, "PatternOrigin"},
	/*    13 */ {PCL_NewDestinationSize, "NewDestinationSize"},
	/*    14 */ {PCL_PrimaryArray, "PrimaryArray"},
	/*    15 */ {PCL_PrimaryDepth, "PrimaryDepth"},
	/*    16 */ {0x00, "Unknow Attribute"},
	/*    17 */ {0x00, "Unknow Attribute"},
	/*    18 */ {0x00, "Unknow Attribute"},
	/*    19 */ {0x00, "Unknow Attribute"},
	/*    20 */ {0x00, "Unknow Attribute"},
	/*    21 */ {0x00, "Unknow Attribute"},
	/*    22 */ {0x00, "Unknow Attribute"},
	/*    23 */ {0x00, "Unknow Attribute"},
	/*    24 */ {0x00, "Unknow Attribute"},
	/*    25 */ {0x00, "Unknow Attribute"},
	/*    26 */ {0x00, "Unknow Attribute"},
	/*    27 */ {0x00, "Unknow Attribute"},
	/*    28 */ {0x00, "Unknow Attribute"},
	/*    29 */ {PCL_AllObjectTypes, "AllObjectTypes"},
	/*    30 */ {PCL_TextObjects, "TextObjects"},
	/*    31 */ {PCL_VectorObjects, "VectorObjects"},
	/*    32 */ {PCL_RasterObjects, "RasterObjects"},
	/*    33 */ {PCL_DeviceMatrix, "DeviceMatrix"},
	/*    34 */ {PCL_DitherMatrixDataType, "DitherMatrixDataType"},
	/*    35 */ {PCL_DitherOrigin, "DitherOrigin"},
	/*    36 */ {PCL_MediaDestination, "MediaDestination"},
	/*    37 */ {PCL_MediaSize, "MediaSize"},
	/*    38 */ {PCL_MediaSource, "MediaSource"},
	/*    39 */ {PCL_MediaType, "MediaType"},
	/*    40 */ {PCL_Orientation, "Orientation"},
	/*    41 */ {PCL_PageAngle, "PageAngle"},
	/*    42 */ {PCL_PageOrigin, "PageOrigin"},
	/*    43 */ {PCL_PageScale, "PageScale"},
	/*    44 */ {PCL_ROP3, "ROP3"},
	/*    45 */ {PCL_TxMode, "TxMode"},
	/*    46 */ {0x00, "Unknow Attribute"},
	/*    47 */ {PCL_CustomMediaSize, "CustomMediaSize"},
	/*    48 */ {PCL_CustomMediaSizeUnits, "CustomMediaSizeUnits"},
	/*    49 */ {PCL_PageCopies, "PageCopies"},
	/*    50 */ {PCL_DitherMatrixSize, "DitherMatrixSize"},
	/*    51 */ {PCL_DitherMatrixDepth, "DitherMatrixDepth"},
	/*    52 */ {PCL_SimplexPageMode, "SimplexPageMode"},
	/*    53 */ {PCL_DuplexPageMode, "DuplexPageMode"},
	/*    54 */ {PCL_DuplexPageSide, "DuplexPageSide"},
	/*    55 */ {0x00, "Unknow Attribute"},
	/*    56 */ {0x00, "Unknow Attribute"},
	/*    57 */ {0x00, "Unknow Attribute"},
	/*    58 */ {0x00, "Unknow Attribute"},
	/*    59 */ {0x00, "Unknow Attribute"},
	/*    60 */ {0x00, "Unknow Attribute"},
	/*    61 */ {0x00, "Unknow Attribute"},
	/*    62 */ {0x00, "Unknow Attribute"},
	/*    63 */ {0x00, "Unknow Attribute"},
	/*    64 */ {0x00, "Unknow Attribute"},
	/*    65 */ {PCL_ArcDirection, "ArcDirection"},
	/*    66 */ {PCL_BoundingBox, "BoundingBox"},
	/*    67 */ {PCL_DashOffset, "DashOffset"},
	/*    68 */ {PCL_EllipseDimension, "EllipseDimension"},
	/*    69 */ {PCL_EndPoint, "EndPoint"},
	/*    70 */ {PCL_FillMode, "FillMode"},
	/*    71 */ {PCL_LineCapStyle, "LineCapStyle"},
	/*    72 */ {PCL_LineJoinStyle, "LineJoinStyle"},
	/*    73 */ {PCL_MiterLength, "MiterLength"},
	/*    74 */ {PCL_LineDashStyle, "LineDashStyle"},
	/*    75 */ {PCL_PenWidth, "PenWidth"},
	/*    76 */ {PCL_Point, "Point"},
	/*    77 */ {PCL_NumberOfPoints, "NumberOfPoints"},
	/*    78 */ {PCL_SolidLine, "SolidLine"},
	/*    79 */ {PCL_StartPoint, "StartPoint"},
	/*    80 */ {PCL_PointType, "PointType"},
	/*    81 */ {PCL_ControlPoint1, "ControlPoint1"},
	/*    82 */ {PCL_ControlPoint2, "ControlPoint2"},
	/*    83 */ {PCL_ClipRegion, "ClipRegion"},
	/*    84 */ {PCL_ClipMode, "ClipMode"},
	/*    85 */ {0x00, "Unknow Attribute"},
	/*    86 */ {0x00, "Unknow Attribute"},
	/*    87 */ {0x00, "Unknow Attribute"},
	/*    88 */ {0x00, "Unknow Attribute"},
	/*    89 */ {0x00, "Unknow Attribute"},
	/*    90 */ {0x00, "Unknow Attribute"},
	/*    91 */ {0x00, "Unknow Attribute"},
	/*    92 */ {0x00, "Unknow Attribute"},
	/*    93 */ {0x00, "Unknow Attribute"},
	/*    94 */ {0x00, "Unknow Attribute"},
	/*    95 */ {0x00, "Unknow Attribute"},
	/*    96 */ {0x00, "Unknow Attribute"},
	/*    97 */ {0x00, "Unknow Attribute"},
	/*    98 */ {PCL_ColorDepth, "ColorDepth"},
	/*    99 */ {PCL_BlockHeight, "BlockHeight"},
	/*   100 */ {PCL_ColorMapping, "ColorMapping"},
	/*   101 */ {PCL_CompressMode, "CompressMode"},
	/*   102 */ {PCL_DestinationBox, "DestinationBox"},
	/*   103 */ {PCL_DestinationSize, "DestinationSize"},
	/*   104 */ {PCL_PatternPersistence, "PatternPersistence"},
	/*   105 */ {PCL_PatternDefineID, "PatternDefineID"},
	/*   106 */ {0x00, "Unknow Attribute"},
	/*   107 */ {PCL_SourceHeight, "SourceHeight"},
	/*   108 */ {PCL_SourceWidth, "SourceWidth"},
	/*   109 */ {PCL_StartLine, "StartLine"},
	/*   110 */ {PCL_XPairType, "XPairType"},
	/*   111 */ {PCL_NumberOfXPairs, "NumberOfXPairs"},
	/*   112 */ {0x00, "Unknow Attribute"},
	/*   113 */ {0x00, "Unknow Attribute"},
	/*   114 */ {0x00, "Unknow Attribute"},
	/*   115 */ {PCL_NumberOfScanLines, "NumberOfScanLines"},
	/*   116 */ {0x00, "Unknow Attribute"},
	/*   117 */ {0x00, "Unknow Attribute"},
	/*   118 */ {0x00, "Unknow Attribute"},
	/*   119 */ {0x00, "Unknow Attribute"},
	/*   120 */ {PCL_ColorTreatment, "ColorTreatment"},
	/*   121 */ {0x00, "Unknow Attribute"},
	/*   122 */ {0x00, "Unknow Attribute"},
	/*   123 */ {0x00, "Unknow Attribute"},
	/*   124 */ {0x00, "Unknow Attribute"},
	/*   125 */ {0x00, "Unknow Attribute"},
	/*   126 */ {0x00, "Unknow Attribute"},
	/*   127 */ {0x00, "Unknow Attribute"},
	/*   128 */ {0x00, "Unknow Attribute"},
	/*   129 */ {PCL_CommentData, "CommentData"},
	/*   130 */ {PCL_DataOrg, "DataOrg"},
	/*   131 */ {0x00, "Unknow Attribute"},
	/*   132 */ {0x00, "Unknow Attribute"},
	/*   133 */ {0x00, "Unknow Attribute"},
	/*   134 */ {PCL_Measure, "Measure"},
	/*   135 */ {0x00, "Unknow Attribute"},
	/*   136 */ {PCL_SourceType, "SourceType"},
	/*   137 */ {PCL_UnitsPerMeasure, "UnitsPerMeasure"},
	/*   138 */ {0x00, "Unknow Attribute"},
	/*   139 */ {PCL_StreamName, "StreamName"},
	/*   140 */ {PCL_StreamDataLength, "StreamDataLength"},
	/*   141 */ {0x00, "Unknow Attribute"}, 
	/*   142 */ {0x00, "Unknow Attribute"},
	/*   143 */ {PCL_ErrorReport, "ErrorReport"},
	/*   144 */ {0x00, "Unknow Attribute"},
	/*   145 */ {0x00, "Unknow Attribute"},
	/*   146 */ {0x00, "Unknow Attribute"},
	/*   147 */ {0x00, "Unknow Attribute"},
	/*   148 */ {0x00, "Unknow Attribute"},
	/*   149 */ {0x00, "Unknow Attribute"},
	/*   150 */ {0x00, "Unknow Attribute"},
	/*   151 */ {0x00, "Unknow Attribute"},
	/*   152 */ {0x00, "Unknow Attribute"},
	/*   153 */ {0x00, "Unknow Attribute"},
	/*   154 */ {0x00, "Unknow Attribute"},
	/*   155 */ {0x00, "Unknow Attribute"},
	/*   156 */ {0x00, "Unknow Attribute"},
	/*   157 */ {0x00, "Unknow Attribute"},
	/*   158 */ {0x00, "Unknow Attribute"},
	/*   159 */ {0x00, "Unknow Attribute"},
	/*   160 */ {0x00, "Unknow Attribute"},
	/*   161 */ {PCL_CharAngle, "CharAngle"},
	/*   162 */ {PCL_CharCode, "CharCode"},
	/*   163 */ {PCL_CharDataSize, "CharDataSize"},
	/*   164 */ {PCL_CharScale, "CharScale"},
	/*   165 */ {PCL_CharShear, "CharShear"},
	/*   166 */ {PCL_CharSize, "CharSize"},
	/*   167 */ {PCL_FontHeaderLength, "FontHeaderLength"},
	/*   168 */ {PCL_FontName, "FontName"},
	/*   169 */ {PCL_FontFormat, "FontFormat"},
	/*   170 */ {PCL_SymbolSet, "SymbolSet"},
	/*   171 */ {PCL_TextData, "TextData"},
	/*   172 */ {PCL_CharSubModeArray, "CharSubModeArray"}, 
	/*   173 */ {PCL_PCLSelectFont, "PCLSelectFont"}, 
	/*   174 */ {0x00, "Unknow Attribute"}, 
	/*   175 */ {PCL_XSpacingData, "XSpacingData"},
	/*   176 */ {PCL_YSpacingData, "YSpacingData"},
	/*   177 */ {PCL_CharBoldValue, "CharBoldValue"},
	/*   178 */ {0x00, "Unknow Attribute"},
	/*   179 */ {0x00, "Unknow Attribute"},
	/*   180 */ {0x00, "Unknow Attribute"},
	/*   181 */ {0x00, "Unknow Attribute"},
	/*   182 */ {0x00, "Unknow Attribute"},
	/*   183 */ {0x00, "Unknow Attribute"},
	/*   184 */ {0x00, "Unknow Attribute"},
	/*   185 */ {0x00, "Unknow Attribute"},
	/*   186 */ {0x00, "Unknow Attribute"},
	/*   187 */ {0x00, "Unknow Attribute"},
	/*   188 */ {0x00, "Unknow Attribute"},
	/*   189 */ {0x00, "Unknow Attribute"},
	/*   190 */ {0x00, "Unknow Attribute"},
	/*   191 */ {0x00, "Unknow Attribute"},
	/*   192 */ {0x00, "Unknow Attribute"},
	/*   193 */ {0x00, "Unknow Attribute"},
	/*   194 */ {0x00, "Unknow Attribute"},
	/*   195 */ {0x00, "Unknow Attribute"},
	/*   196 */ {0x00, "Unknow Attribute"},
	/*   197 */ {0x00, "Unknow Attribute"},
	/*   198 */ {0x00, "Unknow Attribute"},
	/*   199 */ {0x00, "Unknow Attribute"},
	/*   200 */ {0x00, "Unknow Attribute"},
	/*   201 */ {0x00, "Unknow Attribute"},
	/*   202 */ {0x00, "Unknow Attribute"},
	/*   203 */ {0x00, "Unknow Attribute"},
	/*   204 */ {0x00, "Unknow Attribute"},
	/*   205 */ {0x00, "Unknow Attribute"},
	/*   206 */ {0x00, "Unknow Attribute"},
	/*   207 */ {0x00, "Unknow Attribute"},
	/*   208 */ {0x00, "Unknow Attribute"},
	/*   209 */ {0x00, "Unknow Attribute"},
	/*   210 */ {0x00, "Unknow Attribute"},
	/*   211 */ {0x00, "Unknow Attribute"},
	/*   212 */ {0x00, "Unknow Attribute"},
	/*   213 */ {0x00, "Unknow Attribute"},
	/*   214 */ {0x00, "Unknow Attribute"},
	/*   215 */ {0x00, "Unknow Attribute"},
	/*   216 */ {0x00, "Unknow Attribute"},
	/*   217 */ {0x00, "Unknow Attribute"},
	/*   218 */ {0x00, "Unknow Attribute"},
	/*   219 */ {0x00, "Unknow Attribute"},
	/*   220 */ {0x00, "Unknow Attribute"},
	/*   221 */ {0x00, "Unknow Attribute"},
	/*   222 */ {0x00, "Unknow Attribute"},
	/*   223 */ {0x00, "Unknow Attribute"},
	/*   224 */ {0x00, "Unknow Attribute"},
	/*   225 */ {0x00, "Unknow Attribute"},
	/*   226 */ {0x00, "Unknow Attribute"},
	/*   227 */ {0x00, "Unknow Attribute"},
	/*   228 */ {0x00, "Unknow Attribute"},
	/*   229 */ {0x00, "Unknow Attribute"},
	/*   230 */ {0x00, "Unknow Attribute"},
	/*   231 */ {0x00, "Unknow Attribute"},
	/*   232 */ {0x00, "Unknow Attribute"},
	/*   233 */ {0x00, "Unknow Attribute"},
	/*   234 */ {0x00, "Unknow Attribute"},
	/*   235 */ {0x00, "Unknow Attribute"},
	/*   236 */ {0x00, "Unknow Attribute"},
	/*   237 */ {0x00, "Unknow Attribute"},
	/*   238 */ {0x00, "Unknow Attribute"},
	/*   239 */ {0x00, "Unknow Attribute"},
	/*   240 */ {0x00, "Unknow Attribute"},
	/*   241 */ {0x00, "Unknow Attribute"},
	/*   242 */ {0x00, "Unknow Attribute"},
	/*   243 */ {0x00, "Unknow Attribute"},
	/*   244 */ {0x00, "Unknow Attribute"},
	/*   245 */ {0x00, "Unknow Attribute"},
	/*   246 */ {0x00, "Unknow Attribute"},
	/*   247 */ {0x00, "Unknow Attribute"},
	/*   248 */ {0x00, "Unknow Attribute"},
	/*   249 */ {0x00, "Unknow Attribute"},
	/*   250 */ {0x00, "Unknow Attribute"},
	/*   251 */ {0x00, "Unknow Attribute"},
	/*   252 */ {0x00, "Unknow Attribute"},
	/*   253 */ {0x00, "Unknow Attribute"},
	/*   254 */ {0x00, "Unknow Attribute"},
	/*   255 */ {0x00, "Unknow Attribute"}
};

}//命名空间ParsePCL结束
