//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 Install.rc 使用
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_INSTALL_DIALOG              102
#define IDS_EMPTY_SERIAL                102
#define IDS_TIP                         103
#define IDS_WRONG_VERSION               104
#define IDS_WRONG_SERIAL                105
#define IDS_MSG_ClntUpdateSet           106
#define IDS_MSG_MgrUpdateSet            107
#define IDS_MSG_UpdateServSet           108
#define IDR_MAINFRAME                   128
#define IDD_DLG_CREATEDB                129
#define IDD_PAGE_ONE                    130
#define IDD_PAGE_TWO                    131
#define IDD_DLG_SETIP                   132
#define IDD_DIALOG1                     133
#define IDD_DLG_SETDB                   133
#define IDD_DLG_ENCYPT                  135
#define IDD_DLG_CONFIG_PRT              138
#define IDD_DLG_CELERITYSETTING         139
#define IDD_DLG_EXPORT                  140
#define IDD_DLG_TIP                     141
#define IDD_PAGE_THREE                  143
#define IDD_DIALOG2                     144
#define IDD_DLG_CFG_PrtCenterSvr        144
#define IDD_DLG_EMBEDWEB                145
#define IDD_DIALOG3                     146
#define IDB_BITMAP1                     148
#define IDB_APPTITLE                    148
#define IDD_PRTSTATIONWEB_PAGE_ONE      148
#define IDD_PRTSTATIONWEB_PAGE_TWO      149
#define IDD_EMBED_PAGE_ONE              150
#define IDD_PAGE_TWO1                   151
#define IDD_EMBED_PAGE_TWO              151
#define IDD_DLG_YTJ_ADV                 152
#define IDD_DLG_SETHP                   153
#define IDD_DIALOG4                     154
#define IDD_DLG_SETEMBRD_SVR            154
#define IDC_BUTTON1                     1000
#define IDC_IPADDRESS_IP                1000
#define IDC_BUTTON2                     1001
#define IDC_BUTTON3                     1002
#define IDC_IPADDRESS_DBIP              1002
#define IDC_IPADDRESS_IP2               1002
#define IDC_BUTTON4                     1003
#define IDC_EDIT_DBNAME                 1003
#define IDC_BUTTON5                     1004
#define IDC_EDIT_DBPWD                  1004
#define IDC_EDIT_IP                     1004
#define IDC_BUTTON6                     1005
#define IDC_EDIT_DBPORT                 1005
#define IDC_EDIT_USERNAME               1005
#define IDC_BUTTON7                     1006
#define IDC_EDIT_USERPWD                1006
#define IDC_BUTTON8                     1007
#define IDC_TEST                        1007
#define IDC_BUTTON9                     1008
#define IDC_EDIT_PORT                   1008
#define IDC_COMBO_ZHAN                  1008
#define IDC_BUTTON10                    1009
#define IDC_EDIT_WPORT                  1009
#define IDC_BUTTON11                    1010
#define IDC_DEFAULTBOX                  1010
#define IDC_BUTTON12                    1011
#define IDC_BUTTON13                    1012
#define IDC_BUTTON14                    1013
#define IDC_BUTTON15                    1014
#define IDC_BUTTON16                    1015
#define IDC_EDIT1                       1015
#define IDC_RADIO1                      1016
#define IDC_EDIT3                       1016
#define IDC_RADIO2                      1017
#define IDC_EDIT4                       1017
#define IDC_EDIT_DB_SVR                 1018
#define IDC_EDIT5                       1018
#define IDC_EDIT_DB_USER                1019
#define IDC_CHECK1                      1019
#define IDC_CHECK_NEW_WEB               1019
#define IDC_CheckEmbed                  1019
#define IDC_EDIT_DB_PWD                 1020
#define IDC_EDIT6                       1026
#define IDC_BUTTON17                    1030
#define IDC_EDIT2                       1031
#define IDC_STATIC_1                    1032
#define IDC_FONTSIZE                    1032
#define IDC_SIZE9527                    1032
#define IDC_STATIC_2                    1033
#define IDC_EDIT7                       1033
#define IDC_JUMP                        1033
#define IDC_STATIC_3                    1034
#define IDC_COMBO1                      1035
#define IDC_BUTTON18                    1036
#define IDC_IPADDRESS1                  1037
#define IDC_OK                          1038
#define IDC_BTN_CNNT                    1039
#define IDC_COMBO_BRAND                 1039
#define IDC_BTN_SAVE                    1040
#define IDC_COMBO_IP                    1041
#define IDC_BUTTON19                    1042
#define IDC_BTN_ADV                     1043
#define IDC_CHECK_JPG                   1044
#define IDC_CHECK_TIF                   1046
#define IDC_CHECK_SEC                   1047
#define IDC_CHECK_THR                   1048
#define IDC_CHECK_FOUR                  1049
#define IDC_CHECK_FIR                   1050
#define IDC_RADIO_A4                    1051
#define IDC_RADIO_A3                    1052
#define IDC_RADIO_2A4                   1053
#define IDC_RADIO_2A3                   1054
#define IDC_RADIO_3A4                   1055
#define IDC_RADIO_3A3                   1056
#define IDC_RADIO_4A4                   1057
#define IDC_RADIO_4A3                   1058
#define IDC_CHECK_PDF                   1059
#define IDC_RADIO_DZ                    1060
#define IDC_RADIO_KM                    1061
#define IDC_RADIO_SL                    1062
#define IDC_RADIO_LG                    1063
#define IDC_COMBO_DBTYPE                1064
#define IDC_RADIO_SL2                   1064
#define IDC_EDIT_DBADDR                 1065
#define IDC_RADIO_JC                    1065
#define IDC_PROGRESS1                   1066
#define IDC_RADIO_ZD                    1066
#define IDC_EDIT_TIP                    1067
#define IDC_RADIO_ZD2                   1067
#define IDC_RADIO_XP                    1067
#define IDC_RADIO3                      1068
#define IDC_EDIT_WEB_NAME               1068
#define IDC_RADIO_XP2                   1068
#define IDC_RADIO_LM                    1068
#define IDC_RADIO_Enable_Prnter_Meter   1068
#define IDC_RADIO_KM2                   1069
#define IDC_EDIT_WEB_IP                 1069
#define IDC_RADIO_HP                    1069
#define IDC_RADIO_Disable_Printer_Meter 1069
#define IDC_EDIT_WEB_PORT               1070
#define IDC_RADIO_HP2                   1070
#define IDC_RADIO_SX                    1070
#define IDC_STATIC_NEW                  1071
#define IDC_STATIC_NAME                 1072
#define IDC_STATIC_IP                   1073
#define IDC_STATIC_PORT                 1074
#define IDC_SIGNAL_CTRL_USE             1075
#define IDC_SIGNAL_CTRL_NOTUSE          1076
#define IDC_TITLE                       1077
#define IDC_RADIO_Enable_SNMP_Print_Mon 1077
#define IDC_COLOR                       1078
#define IDC_RADIO_Disable_SNMP_Print_Mon 1078
#define IDC_CBOX_WEB                    1081
#define IDOK2                           1088
#define IDC_COMBO_PETWEBDBTYPE          1089
#define IDC_EDIT_PRTWEBIP               1090
#define IDC_EDIT_PRTWEBUSERNAME         1091
#define IDC_EDIT_PRTWEBUSERPWD          1092
#define IDC_EDIT_PRTWEBPORT             1093
#define IDC_EDIT_PRTWEBDBNAME           1094
#define IDC_COMBO_PRTSTATION            1095
#define IDC_EDIT_PRTSTATION_WPORT       1096
#define IDC_PRTSTATION_TEST             1097
#define IDC_CHECK_PRTSTATION_NEW_WEB    1098
#define IDC_EDIT_PRTSTATION_WEB_NAME    1099
#define IDC_EDIT_PRTSTATION_WEB_IP      1100
#define IDC_EDIT_PRTSTATION_WEB_PORT    1101
#define IDC_RADIO_EMBED_TYPE_NO         1104
#define IDC_RADIO_EMBED_TYPE_LISTEN     1105
#define IDC_RADIO_EMBED_TYPE_CONNECT    1106
#define IDC_RADIO_EMBED_TYPE_DB         1107
#define IDC_LISTEN_PORT                 1108
#define IDC_STATIC_LISTENPORT           1109
#define IDC_BTN_YTJ_ADV                 1110
#define IDC_COMBO_PRINTER_ADV_MODE      1111
#define IDC_EDIT_productName            1112
#define IDC_EDIT_productID              1113
#define IDC_EDIT_serialNo               1114
#define IDC_EDIT_CopyBak                1115
#define IDC_RADIO4                      1116
#define IDC_CHECK2                      1117
#define IDC_CHECK_CopyBak               1117
#define IDC_RADIO_HPENT                 1118
#define IDC_RADIO_HPPRO                 1119
#define IDC_REGACCTIME                  1120
#define IDC_REGACCURL                   1121
#define IDC_BUTTON_CopyBak              1122
#define IDC_ENBEDED_CORESVRIP           1123
#define IDC_ENBEDED_CORESVRPORT         1124
#define IDC_BTN_TESTCNNT                1125
#define IDC_ENBEDED_WEBSVRPORT          1126
#define IDC_BTN_TESTCNNT2               1127

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        156
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1126
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
